[workspace]
members = [
    "infernum",
    "infernum-examples",
    "infernum-gemma",
    "infernum-llama",
    "infernum-macros",
    "infernum-qwen",
    "infernum-runtime",
    "infernum-serve",
]
resolver = "2"